FROM node:20-alpine
WORKDIR /app
COPY ../../package.json ../../pnpm-workspace.yaml ../../pnpm-lock.yaml* ./
RUN npm install -g pnpm
COPY ../../ ./
RUN pnpm install --frozen-lockfile
RUN pnpm --filter web build
CMD ["pnpm", "--filter", "web", "start"]
