FROM node:20-alpine AS base
WORKDIR /app
COPY ../../package.json ../../pnpm-workspace.yaml ../../pnpm-lock.yaml* ./
RUN npm install -g pnpm
COPY ../../ ./
RUN pnpm install --frozen-lockfile
RUN pnpm --filter api build
CMD ["node", "dist/main.js"]
